name: CD

on:
  push:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/developmentsucks-api:latest ./backend

      - name: Build frontend image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/developmentsucks-client:latest ./frontend

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/developmentsucks-api:latest

      - name: Push frontend image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/developmentsucks-client:latest
