name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Клонировать репозиторий
      uses: actions/checkout@v4

    - name: Установить .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Восстановить зависимости
      run: dotnet restore backend/DevelopmentSucks.sln

    - name: Сборка проекта
      run: dotnet build backend/DevelopmentSucks.sln --no-restore --configuration Release

    - name: Запуск тестов
      run: dotnet test backend/DevelopmentSucks.sln --no-build --configuration Release

    - name: Установить Node.js
      uses: actions/setup-node@v4
      with: 
        node-version: '20'

    - name: Установка зависимостей frontend
      working-directory: ./frontend
      run: npm install

    - name: Сборка frontend
      working-directory: ./frontend
      run: npm run build
